/**
 * Ngữ pháp N3.
 *
 * Cái khó của N3 không nằm ở số lượng mẫu mà ở việc phân biệt các mẫu gần
 * nghĩa nhau — đề thi hỏi đúng chỗ đó. Vì vậy phần ghi chú của mỗi mẫu ưu tiên
 * nói rõ nó khác mẫu nào, thay vì chỉ dịch nghĩa.
 *
 * Định dạng giống GRAMMAR/GRAMMAR4: [mẫu, nghĩa, ghi chú, [[câu Nhật, dịch]]]
 */
import { validateGrammarRows } from "./validate";

export const GRAMMAR_N3: (string | string[][])[][] = validateGrammarRows([
  ["～について","về, xoay quanh","Dùng khi nội dung nói/nghĩ/viết xoay quanh chủ đề nào đó. Trung tính. Khác ～に対して ở chỗ について là <b>chủ đề</b>, còn に対して là <b>đối tượng hướng tới</b>.",
   [["日本の文化について研究しています。","Tôi đang nghiên cứu về văn hóa Nhật."]]],
  ["～に対して","đối với, nhằm vào","Chỉ đối tượng mà thái độ hay hành động hướng tới. Còn nghĩa thứ hai là đối lập: A に対して B nghĩa là ngược lại với A thì B.",
   [["先生に対して失礼なことを言ってしまった。","Tôi đã lỡ nói điều thất lễ với thầy."],["兄は静かなのに対して、弟はよく話す。","Anh thì trầm, ngược lại em trai nói nhiều."]]],
  ["～によって","do, bởi, tùy theo","Ba nghĩa hay gặp: nguyên nhân, phương tiện, và \"tùy theo\". Trong câu bị động thì chỉ người thực hiện (この本は夏目漱石によって書かれた).",
   [["人によって考え方が違う。","Tùy người mà cách nghĩ khác nhau."],["事故によって電車が遅れた。","Tàu trễ do tai nạn."]]],
  ["～において","tại, trong (trang trọng)","Bản trang trọng của で, dùng trong văn viết và bối cảnh chính thức. Nói chuyện thường ngày thì dùng で.",
   [["会議は東京において行われる。","Cuộc họp được tổ chức tại Tokyo."]]],
  ["～に関して","liên quan đến","Trang trọng hơn ～について, hay gặp trong văn bản và tin tức.",
   [["この件に関して質問があります。","Tôi có câu hỏi liên quan đến việc này."]]],
  ["～にとって","đối với ai đó (mà nói)","Đứng ở lập trường của ai để đánh giá. Vế sau thường là tính từ đánh giá: 大切, 大変, 難しい.",
   [["私にとって家族が一番大切です。","Với tôi, gia đình là quan trọng nhất."]]],
  ["～として","với tư cách là","Chỉ tư cách, vai trò, danh nghĩa.",
   [["留学生として日本に来ました。","Tôi đến Nhật với tư cách du học sinh."]]],
  ["～に比べて","so với","So sánh hai đối tượng. Trang trọng hơn より.",
   [["去年に比べて、今年は暑い。","So với năm ngoái, năm nay nóng."]]],
  ["～に応じて","tùy theo, tương ứng với","Thay đổi linh hoạt theo cái gì đó. Khác ～によって ở chỗ に応じて nhấn sự <b>điều chỉnh cho phù hợp</b>.",
   [["収入に応じて税金を払う。","Đóng thuế tùy theo thu nhập."]]],
  ["～につれて","càng… thì càng…","Hai bên biến đổi song song, tự nhiên, không có ý chí. Gần nghĩa với ～にしたがって.",
   [["年をとるにつれて、体が弱くなる。","Càng lớn tuổi thì cơ thể càng yếu đi."]]],
  ["～にしたがって","theo, cùng với","Vừa nghĩa \"càng… càng…\" như につれて, vừa nghĩa \"làm theo\" (mệnh lệnh, quy tắc).",
   [["説明書にしたがって組み立てる。","Lắp ráp theo bản hướng dẫn."]]],
  ["～とともに","cùng với, đồng thời","Vừa nghĩa \"cùng nhau\", vừa nghĩa hai việc xảy ra đồng thời.",
   [["技術の進歩とともに生活が便利になった。","Cùng với tiến bộ kỹ thuật, cuộc sống tiện lợi hơn."]]],
  ["～おかげで","nhờ có","Kết quả <b>tốt</b>. Cặp đối nghĩa là ～せいで.",
   [["先生のおかげで合格できました。","Nhờ có thầy mà em đã đỗ."]]],
  ["～せいで","tại vì (kết quả xấu)","Kết quả <b>xấu</b>, kèm ý trách móc. Đừng dùng khi kết quả tốt.",
   [["雨のせいで試合が中止になった。","Tại mưa mà trận đấu bị hủy."]]],
  ["～くせに","mặc dù… vậy mà","Giống のに nhưng mang rõ ý <b>chê trách, coi thường</b>, nên không dùng với người trên.",
   [["知っているくせに教えてくれない。","Biết mà vậy mà không chỉ cho."]]],
  ["～わけだ","hóa ra là, thảo nào","Người nói vừa hiểu ra lý do của điều đã thấy. Khác はず ở chỗ わけだ là <b>hiểu ra sau khi biết nguyên nhân</b>.",
   [["10年住んでいたのか。日本語が上手なわけだ。","Sống 10 năm à. Thảo nào tiếng Nhật giỏi."]]],
  ["～わけではない","không hẳn là","Phủ định nhẹ, đính chính một suy đoán. Không phải phủ định hoàn toàn.",
   [["日本語が嫌いなわけではないが、難しい。","Không hẳn là ghét tiếng Nhật, nhưng nó khó."]]],
  ["～わけがない","không đời nào","Phủ định mạnh, khẳng định điều đó bất khả. Gần nghĩa ～はずがない.",
   [["彼がそんなことを言うわけがない。","Không đời nào anh ấy nói vậy."]]],
  ["～わけにはいかない","không thể (vì lý do xã hội)","Không phải không có khả năng, mà là hoàn cảnh hoặc lẽ phải không cho phép. Khác hẳn ～ことができない.",
   [["明日は試験だから、休むわけにはいかない。","Mai thi nên không thể nghỉ được."]]],
  ["～に違いない","chắc chắn là","Suy đoán rất chắc của người nói, mạnh hơn ～だろう và ～はずだ.",
   [["この字は田中さんが書いたに違いない。","Chữ này chắc chắn là anh Tanaka viết."]]],
  ["～はずがない","không thể nào","Suy luận có căn cứ rằng điều đó không thể. Ôn lại: ～はずだ ở N4 là \"chắc chắn có\".",
   [["こんな簡単な問題を間違えるはずがない。","Không thể nào sai câu dễ thế này."]]],
  ["～たばかり","vừa mới xong","Chủ quan: người nói <b>cảm thấy</b> vừa mới. Khác ～たところ ở chỗ たところ là thực tế vừa xong tính bằng phút.",
   [["先月日本に来たばかりです。","Tôi vừa mới sang Nhật tháng trước."]]],
  ["～ところだ","sắp / đang / vừa xong","Ba dạng: 食べるところ (sắp ăn), 食べているところ (đang ăn), 食べたところ (vừa ăn xong).",
   [["今、家を出るところです。","Bây giờ tôi sắp ra khỏi nhà."],["ちょうど食べ終わったところです。","Vừa đúng lúc ăn xong."]]],
  ["～ばかり","toàn là, chỉ mỗi","Chê trách rằng chỉ có mỗi thứ đó, lặp đi lặp lại.",
   [["弟はゲームばかりしている。","Em trai suốt ngày chỉ chơi game."]]],
  ["～ばかりでなく／だけでなく","không những… mà còn","Vế sau thường có も. ばかりでなく trang trọng hơn だけでなく.",
   [["彼は英語だけでなく、中国語も話せる。","Anh ấy không những nói được tiếng Anh mà còn cả tiếng Trung."]]],
  ["～うちに","trong lúc còn…","Làm gì trong khoảng thời gian trạng thái đó còn duy trì, ngụ ý sau đó sẽ mất đi.",
   [["熱いうちに食べてください。","Hãy ăn khi còn nóng."]]],
  ["～ないうちに","trước khi… xảy ra","Làm gì trước khi trạng thái thay đổi.",
   [["暗くならないうちに帰りましょう。","Về thôi, trước khi trời tối."]]],
  ["～最中に","đang giữa lúc","Nhấn mạnh đúng lúc đang cao trào thì có việc xen vào.",
   [["食事の最中に電話がかかってきた。","Đang giữa bữa ăn thì có điện thoại."]]],
  ["～たとたん","vừa mới… thì đột nhiên","Hai việc nối nhau tức thì, vế sau là điều <b>ngoài dự tính</b>. Không dùng cho việc có ý chí.",
   [["ドアを開けたとたん、猫が飛び出した。","Vừa mở cửa thì con mèo lao ra."]]],
  ["～たびに","cứ mỗi lần","Lần nào cũng vậy, không ngoại lệ.",
   [["彼に会うたびに、昔を思い出す。","Cứ mỗi lần gặp anh ấy là tôi nhớ chuyện xưa."]]],
  ["～まま","cứ để nguyên trạng thái","Ôn từ N4 và mở rộng: trạng thái bất thường được giữ nguyên trong lúc làm việc khác.",
   [["靴を履いたまま入らないでください。","Xin đừng đi cả giày vào."]]],
  ["～ずに","không làm gì mà…","Dạng văn viết của ～ないで. Riêng する thành せずに.",
   [["朝ごはんを食べずに学校へ行った。","Tôi đi học mà không ăn sáng."]]],
  ["～ながらも","tuy… nhưng","Khác ～ながら chỉ \"vừa… vừa…\": thêm も thành ý nhượng bộ, tương đương のに.",
   [["狭いながらも、楽しい我が家。","Tuy chật nhưng là mái nhà vui vẻ của tôi."]]],
  ["～きり","kể từ đó rồi thôi","Sau việc đó thì trạng thái không đổi nữa, thường kèm ý tiếc nuối.",
   [["彼とは10年前に会ったきりです。","Tôi gặp anh ấy 10 năm trước rồi thôi, từ đó không gặp lại."]]],
  ["～かけ","đang dở, chưa xong","Bỏ ます + かけ. Việc bắt đầu rồi mà chưa hoàn tất.",
   [["読みかけの本が机の上にある。","Cuốn sách đọc dở nằm trên bàn."]]],
  ["～きる／～きれない","làm trọn / không nổi","Bỏ ます + きる. きれない nghĩa là nhiều quá không xuể.",
   [["この量は一人では食べきれない。","Lượng này một mình ăn không hết nổi."]]],
  ["～がち","hay bị, thường hay","Khuynh hướng, gần như luôn mang nghĩa <b>tiêu cực</b>.",
   [["冬は風邪をひきがちです。","Mùa đông hay bị cảm."]]],
  ["～気味","hơi có vẻ","Cảm thấy có chút dấu hiệu, cũng thiên về nghĩa tiêu cực.",
   [["ちょっと風邪気味です。","Tôi hơi bị cảm."]]],
  ["～っぽい","có vẻ, dễ bị","Khẩu ngữ. 子どもっぽい (trẻ con), 忘れっぽい (hay quên).",
   [["彼の話は嘘っぽい。","Chuyện anh ta kể nghe có vẻ xạo."]]],
  ["～だらけ","đầy những (thứ xấu)","Bám đầy, dính đầy — luôn tiêu cực. Khác ～いっぱい trung tính.",
   [["子どもが泥だらけになって帰ってきた。","Thằng bé về nhà lấm đầy bùn."]]],
  ["～向け／～向き","dành cho / hợp với","向け là <b>cố ý làm cho</b> đối tượng đó; 向き là <b>tình cờ hợp</b> với đối tượng đó.",
   [["これは子ども向けの本です。","Đây là sách dành cho trẻ em."],["この部屋は南向きで明るい。","Phòng này hướng nam nên sáng."]]],
  ["～ほど","đến mức","Diễn tả mức độ bằng một hình ảnh cụ thể.",
   [["立てないほど疲れた。","Mệt đến mức không đứng nổi."]]],
  ["～ば～ほど","càng… càng…","Cấu trúc kép: thể ば + thể từ điển + ほど.",
   [["練習すればするほど上手になる。","Càng luyện thì càng giỏi."]]],
  ["～さえ","ngay cả… cũng","Nêu ví dụ cực đoan để nhấn mạnh.",
   [["漢字どころか、ひらがなさえ読めない。","Đừng nói kanji, ngay cả hiragana cũng không đọc được."]]],
  ["～さえ～ば","chỉ cần… là được","Điều kiện duy nhất cần thiết.",
   [["お金さえあれば、何でもできる。","Chỉ cần có tiền thì làm gì cũng được."]]],
  ["～しかない","chỉ còn cách","Không còn lựa chọn nào khác.",
   [["終電がないから、歩いて帰るしかない。","Hết tàu cuối rồi nên chỉ còn cách đi bộ về."]]],
  ["～べきだ","nên (về mặt đạo lý)","Điều đúng đắn nên làm. Nặng hơn ～たほうがいい. する thành すべき hoặc するべき.",
   [["約束は守るべきだ。","Đã hứa thì nên giữ lời."]]],
  ["～ことはない","không cần phải","Khuyên rằng không cần thiết làm điều đó.",
   [["心配することはないよ。","Không cần phải lo đâu."]]],
  ["～ものだ","vốn dĩ, thường là","Nêu lẽ thường, chân lý chung. Dạng ～たものだ là hồi tưởng \"hồi xưa hay…\".",
   [["年をとると、昔のことを思い出すものだ。","Có tuổi rồi thì người ta thường nhớ chuyện xưa."]]],
  ["～ようがない","không có cách nào","Muốn làm cũng không có cách. Bỏ ます + ようがない.",
   [["連絡先が分からないので、知らせようがない。","Không biết địa chỉ liên lạc nên không có cách nào báo."]]],
  ["～とおりに","đúng như, y như","Làm giống hệt cái đã nêu.",
   [["先生が言ったとおりにやってください。","Hãy làm đúng như thầy đã nói."]]],
  ["～かわりに","thay vì, bù lại","Vừa nghĩa thay thế, vừa nghĩa bù trừ.",
   [["外食するかわりに、家で料理した。","Thay vì ăn ngoài, tôi nấu ở nhà."]]],
  ["～一方で","một mặt thì… mặt khác","Nêu hai mặt song song của cùng một sự việc.",
   [["彼は厳しい一方で、優しいところもある。","Anh ấy một mặt nghiêm khắc, mặt khác cũng có chỗ dịu dàng."]]],
  ["～てほしい","muốn ai đó làm gì","Chủ ngữ mong người khác làm. Khác ～たい (tự mình muốn làm).",
   [["もう少し待ってほしいです。","Tôi muốn anh đợi thêm chút nữa."]]],
  ["～ようにする","cố gắng để (thành thói quen)","Nỗ lực có ý thức. Khác ～ようになる ở N4 là sự thay đổi tự nhiên.",
   [["毎日野菜を食べるようにしています。","Tôi đang cố ăn rau mỗi ngày."]]],
  ["～ことになっている","theo quy định thì","Quy tắc, lịch trình đã được định sẵn, không phải ý mình.",
   [["会議は9時から始まることになっています。","Theo quy định thì cuộc họp bắt đầu từ 9 giờ."]]],
  ["使役受身形","bị bắt phải làm","Ghép sai khiến với bị động: 行かせられる／行かされる. Mang ý miễn cưỡng, khó chịu.",
   [["部長にお酒を飲まされた。","Tôi bị trưởng phòng ép uống rượu."]]],
  ["尊敬語","kính ngữ tôn kính","Nâng người khác lên. Động từ đặc biệt: 行く→いらっしゃる, 食べる→召し上がる, 言う→おっしゃる, 見る→ご覧になる.",
   [["先生はもういらっしゃいましたか。","Thầy đã đến chưa ạ?"]]],
  ["謙譲語","kính ngữ khiêm nhường","Hạ mình xuống. Động từ đặc biệt: 行く→伺う, 言う→申す, する→いたす, 見る→拝見する.",
   [["明日、伺ってもよろしいでしょうか。","Ngày mai em đến thăm có được không ạ?"]]],
  ["～とか","nghe nói là (không chắc)","Truyền đạt thông tin mà mình không chắc chắn.",
   [["彼は来月結婚するとか。","Nghe nói tháng sau anh ấy cưới."]]],
  ["～って","nghe nói, rằng (khẩu ngữ)","Dạng nói tắt của ～と言っていた hoặc ～というのは. Chỉ dùng khi nói chuyện thân mật.",
   [["田中さん、明日来ないって。","Anh Tanaka bảo mai không đến."]]],
  ["～ということだ","tức là, nghe nói là","Truyền đạt lại nguyên văn, hoặc kết luận diễn giải.",
   [["天気予報によると、明日は雪だということだ。","Theo dự báo thì nghe nói mai có tuyết."]]],
  ["～みたいに／～みたいな","giống như","Khẩu ngữ của ～ように／～ような.",
   [["彼は子どもみたいに喜んだ。","Anh ấy mừng như trẻ con."]]],
  ["～らしい","có vẻ, đúng chất","Hai nghĩa: suy đoán theo tin nghe được, và \"đúng chất\" (男らしい, 学生らしい).",
   [["今日は春らしい天気ですね。","Hôm nay thời tiết đúng chất mùa xuân nhỉ."]]],
  ["～ないことはない","không phải là không","Phủ định của phủ định, khẳng định dè dặt.",
   [["辛い物も食べないことはない。","Đồ cay thì cũng không phải là không ăn được."]]],
  ["～に決まっている","chắc chắn là (chủ quan)","Người nói tin chắc, nhưng là niềm tin chủ quan chứ không có căn cứ rõ như に違いない.",
   [["こんな時間に電話するなんて、寝ているに決まっている。","Gọi giờ này thì chắc chắn người ta đang ngủ rồi."]]],
], "ngữ pháp N3");
