/**
 * Từ vựng N3 — đợt hai: đời sống, sức khỏe, thiên nhiên, giao thông.
 */
import { validateVocabGroups } from "./validate";

export const VOCAB_N3_B: [string, string[][]][] = validateVocabGroups([
  ["Sức khỏe &amp; cơ thể", [
    ["体調","たいちょう","taichō","tình trạng sức khỏe"],
    ["症状","しょうじょう","shōjō","triệu chứng"],
    ["風邪","かぜ","kaze","cảm lạnh"],
    ["熱","ねつ","netsu","cơn sốt"],
    ["痛み","いたみ","itami","cơn đau"],
    ["怪我","けが","kega","vết thương"],
    ["薬","くすり","kusuri","thuốc"],
    ["注射","ちゅうしゃ","chūsha","tiêm"],
    ["検査","けんさ","kensa","xét nghiệm, kiểm tra"],
    ["手術","しゅじゅつ","shujutsu","phẫu thuật"],
    ["入院","にゅういん","nyūin","nhập viện"],
    ["退院","たいいん","taiin","xuất viện"],
    ["医者","いしゃ","isha","bác sĩ"],
    ["患者","かんじゃ","kanja","bệnh nhân"],
    ["睡眠","すいみん","suimin","giấc ngủ"],
    ["疲れ","つかれ","tsukare","sự mệt mỏi"],
  ]],
  ["Giao thông &amp; đi lại", [
    ["交通","こうつう","kōtsū","giao thông"],
    ["渋滞","じゅうたい","jūtai","tắc đường"],
    ["満員","まんいん","man'in","chật kín người"],
    ["乗り換え","のりかえ","norikae","việc chuyển tàu, đổi tuyến"],
    ["各駅","かくえき","kakueki","tàu thường, dừng mọi ga"],
    ["急行","きゅうこう","kyūkō","tàu tốc hành"],
    ["指定席","していせき","shiteiseki","ghế đặt trước"],
    ["自由席","じゆうせき","jiyūseki","ghế tự do"],
    ["片道","かたみち","katamichi","một chiều"],
    ["往復","おうふく","ōfuku","khứ hồi"],
    ["出発","しゅっぱつ","shuppatsu","khởi hành"],
    ["到着","とうちゃく","tōchaku","đến nơi"],
    ["遅刻","ちこく","chikoku","đi trễ"],
    ["移動","いどう","idō","di chuyển"],
    ["距離","きょり","kyori","khoảng cách"],
    ["方向","ほうこう","hōkō","phương hướng"],
  ]],
  ["Thiên nhiên &amp; thời tiết", [
    ["天候","てんこう","tenkō","thời tiết"],
    ["気温","きおん","kion","nhiệt độ không khí"],
    ["湿度","しつど","shitsudo","độ ẩm"],
    ["台風","たいふう","taifū","bão"],
    ["地震","じしん","jishin","động đất"],
    ["洪水","こうずい","kōzui","lũ lụt"],
    ["自然","しぜん","shizen","tự nhiên"],
    ["海岸","かいがん","kaigan","bờ biển"],
    ["森林","しんりん","shinrin","rừng"],
    ["景色","けしき","keshiki","phong cảnh"],
    ["空気","くうき","kūki","không khí"],
    ["太陽","たいよう","taiyō","mặt trời"],
    ["季節","きせつ","kisetsu","mùa"],
    ["温度","おんど","ondo","nhiệt độ"],
  ]],
  ["Nhà cửa &amp; sinh hoạt", [
    ["生活","せいかつ","seikatsu","đời sống"],
    ["家事","かじ","kaji","việc nhà"],
    ["掃除","そうじ","sōji","dọn dẹp"],
    ["洗濯","せんたく","sentaku","giặt giũ"],
    ["片付け","かたづけ","katazuke","việc dọn gọn"],
    ["家賃","やちん","yachin","tiền thuê nhà"],
    ["引っ越し","ひっこし","hikkoshi","chuyển nhà"],
    ["近所","きんじょ","kinjo","hàng xóm, lân cận"],
    ["留守","るす","rusu","vắng nhà"],
    ["準備","じゅんび","junbi","chuẩn bị"],
    ["用意","ようい","yōi","sự chuẩn bị"],
    ["予約","よやく","yoyaku","đặt trước"],
    ["修理","しゅうり","shūri","sửa chữa"],
    ["故障","こしょう","koshō","hỏng hóc"],
    ["電気代","でんきだい","denkidai","tiền điện"],
    ["支払い","しはらい","shiharai","việc thanh toán"],
  ]],
  ["Học tập &amp; giao tiếp", [
    ["返事","へんじ","henji","hồi âm"],
    ["連絡","れんらく","renraku","liên lạc"],
    ["相談","そうだん","sōdan","bàn bạc"],
    ["紹介","しょうかい","shōkai","giới thiệu"],
    ["招待","しょうたい","shōtai","lời mời"],
    ["訪問","ほうもん","hōmon","thăm viếng"],
    ["約束","やくそく","yakusoku","lời hứa"],
    ["許可","きょか","kyoka","sự cho phép"],
    ["出席","しゅっせき","shusseki","có mặt"],
    ["欠席","けっせき","kesseki","vắng mặt"],
    ["宿題","しゅくだい","shukudai","bài tập về nhà"],
    ["復習","ふくしゅう","fukushū","ôn lại"],
    ["予習","よしゅう","yoshū","chuẩn bị bài trước"],
    ["成績","せいせき","seiseki","thành tích, điểm"],
    ["合格","ごうかく","gōkaku","đỗ, đạt"],
    ["留学","りゅうがく","ryūgaku","du học"],
  ]],
], "từ vựng N3 đợt 2");
