/**
 * Từ vựng N3 theo chủ đề.
 *
 * Định dạng giống N5/N4V: [nhãn nhóm, [[chữ viết, cách đọc, romaji, nghĩa]]]
 */
export const VOCAB_N3: [string, string[][]][] = [
  ["Xã hội &amp; thời sự", [
    ["社会","しゃかい","shakai","xã hội"],
    ["政治","せいじ","seiji","chính trị"],
    ["経済","けいざい","keizai","kinh tế"],
    ["情報","じょうほう","jōhō","thông tin"],
    ["環境","かんきょう","kankyō","môi trường"],
    ["国際","こくさい","kokusai","quốc tế"],
    ["地域","ちいき","chiiki","khu vực, địa phương"],
    ["政府","せいふ","seifu","chính phủ"],
    ["法律","ほうりつ","hōritsu","pháp luật"],
    ["制度","せいど","seido","chế độ"],
    ["文化","ぶんか","bunka","văn hóa"],
    ["歴史","れきし","rekishi","lịch sử"],
    ["伝統","でんとう","dentō","truyền thống"],
    ["技術","ぎじゅつ","gijutsu","kỹ thuật"],
    ["科学","かがく","kagaku","khoa học"],
    ["産業","さんぎょう","sangyō","ngành công nghiệp"],
    ["事件","じけん","jiken","vụ việc, vụ án"],
    ["事故","じこ","jiko","tai nạn"],
    ["被害","ひがい","higai","thiệt hại"],
    ["災害","さいがい","saigai","thiên tai"],
  ]],
  ["Công việc &amp; tổ chức", [
    ["企業","きぎょう","kigyō","doanh nghiệp"],
    ["組織","そしき","soshiki","tổ chức"],
    ["責任","せきにん","sekinin","trách nhiệm"],
    ["能力","のうりょく","nōryoku","năng lực"],
    ["経験","けいけん","keiken","kinh nghiệm"],
    ["面接","めんせつ","mensetsu","phỏng vấn"],
    ["給料","きゅうりょう","kyūryō","tiền lương"],
    ["条件","じょうけん","jōken","điều kiện"],
    ["契約","けいやく","keiyaku","hợp đồng"],
    ["担当","たんとう","tantō","phụ trách"],
    ["報告","ほうこく","hōkoku","báo cáo"],
    ["確認","かくにん","kakunin","xác nhận"],
    ["提出","ていしゅつ","teishutsu","nộp, đệ trình"],
    ["締め切り","しめきり","shimekiri","hạn chót"],
    ["作業","さぎょう","sagyō","công việc, thao tác"],
    ["効果","こうか","kōka","hiệu quả"],
    ["目的","もくてき","mokuteki","mục đích"],
    ["目標","もくひょう","mokuhyō","mục tiêu"],
    ["計画","けいかく","keikaku","kế hoạch"],
    ["実際","じっさい","jissai","thực tế"],
  ]],
  ["Suy nghĩ &amp; cảm xúc", [
    ["意見","いけん","iken","ý kiến"],
    ["判断","はんだん","handan","phán đoán"],
    ["理解","りかい","rikai","sự hiểu"],
    ["知識","ちしき","chishiki","kiến thức"],
    ["記憶","きおく","kioku","ký ức"],
    ["印象","いんしょう","inshō","ấn tượng"],
    ["態度","たいど","taido","thái độ"],
    ["性格","せいかく","seikaku","tính cách"],
    ["感情","かんじょう","kanjō","cảm xúc"],
    ["希望","きぼう","kibō","hy vọng"],
    ["不安","ふあん","fuan","bất an, lo lắng"],
    ["満足","まんぞく","manzoku","hài lòng"],
    ["我慢","がまん","gaman","chịu đựng, nhẫn nhịn"],
    ["緊張","きんちょう","kinchō","căng thẳng, hồi hộp"],
    ["感動","かんどう","kandō","cảm động"],
    ["後悔","こうかい","kōkai","hối hận"],
    ["自信","じしん","jishin","tự tin"],
    ["興味","きょうみ","kyōmi","hứng thú"],
    ["夢","ゆめ","yume","giấc mơ, ước mơ"],
    ["苦手","にがて","nigate","kém, ngại (việc gì)"],
  ]],
  ["Động từ N3", [
    ["含む","ふくむ","fukumu","bao gồm"],
    ["超える","こえる","koeru","vượt quá"],
    ["求める","もとめる","motomeru","yêu cầu, tìm kiếm"],
    ["与える","あたえる","ataeru","cho, trao"],
    ["認める","みとめる","mitomeru","công nhận, thừa nhận"],
    ["示す","しめす","shimesu","chỉ ra, thể hiện"],
    ["表す","あらわす","arawasu","biểu đạt"],
    ["比べる","くらべる","kuraberu","so sánh"],
    ["変わる","かわる","kawaru","thay đổi"],
    ["増える","ふえる","fueru","tăng lên"],
    ["減る","へる","heru","giảm đi"],
    ["続く","つづく","tsuzuku","tiếp diễn"],
    ["進む","すすむ","susumu","tiến lên"],
    ["育てる","そだてる","sodateru","nuôi dạy"],
    ["守る","まもる","mamoru","bảo vệ, giữ lời"],
    ["防ぐ","ふせぐ","fusegu","ngăn ngừa"],
    ["断る","ことわる","kotowaru","từ chối"],
    ["諦める","あきらめる","akirameru","từ bỏ"],
    ["忘れる","わすれる","wasureru","quên"],
    ["確かめる","たしかめる","tashikameru","kiểm chứng"],
    ["役立つ","やくだつ","yakudatsu","có ích"],
    ["溜まる","たまる","tamaru","tích tụ, dồn lại"],
    ["慣れる","なれる","nareru","quen với"],
    ["試す","ためす","tamesu","thử"],
  ]],
  ["Trạng từ &amp; liên từ N3", [
    ["実は","じつは","jitsu wa","thật ra thì"],
    ["確か","たしか","tashika","hình như, nếu tôi nhớ không nhầm"],
    ["結局","けっきょく","kekkyoku","rốt cuộc"],
    ["さらに","さらに","sarani","hơn nữa"],
    ["むしろ","むしろ","mushiro","thà rằng, đúng hơn là"],
    ["やはり","やはり","yahari","quả nhiên, đúng như nghĩ"],
    ["しかも","しかも","shikamo","hơn nữa, mà lại"],
    ["ただし","ただし","tadashi","tuy nhiên, với điều kiện"],
    ["一方","いっぽう","ippō","mặt khác"],
    ["つまり","つまり","tsumari","tức là"],
    ["例えば","たとえば","tatoeba","ví dụ"],
    ["および","および","oyobi","và (văn viết)"],
    ["ほぼ","ほぼ","hobo","gần như"],
    ["せっかく","せっかく","sekkaku","cất công, khó khăn lắm mới"],
    ["わざわざ","わざわざ","wazawaza","cất công, cố ý"],
    ["さすが","さすが","sasuga","quả không hổ danh"],
    ["どうせ","どうせ","dōse","đằng nào cũng"],
    ["せめて","せめて","semete","ít nhất thì"],
    ["まさか","まさか","masaka","chẳng lẽ, không ngờ"],
    ["ほとんど","ほとんど","hotondo","hầu hết, hầu như không"],
  ]],
];
